export const themes = {
  warm: {
    background: "bg-yellow-100",
    text: "text-yellow-900",
    button: "bg-yellow-500 hover:bg-yellow-600 active:bg-yellow-700 text-black",
    activeTab: "bg-yellow-700 text-white font-bold shadow-md",
    sliderTrack: "bg-yellow-300",
    sliderFill: "bg-yellow-500",
    sliderThumb: "bg-yellow-700",
    sliderValue: "bg-yellow-800 text-white",
    toggleBackground: "bg-yellow-300",
    toggleThumb: "bg-yellow-400",
    toggleActive: "bg-yellow-500",
    toggleInactive: "bg-yellow-200",
    input:
      "border border-yellow-400 bg-yellow-50 text-yellow-900 placeholder-yellow-600 focus:ring-2 focus:ring-yellow-500",
    dropdownHover: "hover:bg-yellow-300",
    collapseContainer: "border border-yellow-400 bg-yellow-50",
    collapseHeader: "bg-yellow-200 text-yellow-900 cursor-pointer",
    collapseContent: "bg-yellow-100 text-yellow-800",
    collapseIcon: "text-yellow-700 transition-transform duration-300",
  },

  cool: {
    background: "bg-blue-100",
    text: "text-blue-900",
    button: "bg-blue-500 hover:bg-blue-600 active:bg-blue-700 text-white",
    activeTab: "bg-blue-700 text-white font-bold shadow-md",
    sliderTrack: "bg-blue-300",
    sliderFill: "bg-blue-500",
    sliderThumb: "bg-blue-700",
    sliderValue: "bg-blue-800 text-white",
    toggleBackground: "bg-blue-300",
    toggleThumb: "bg-blue-400",
    toggleActive: "bg-blue-500",
    toggleInactive: "bg-blue-200",
    input:
      "border border-blue-400 bg-blue-50 text-blue-900 placeholder-blue-600 focus:ring-2 focus:ring-blue-500",
    dropdownHover: "hover:bg-blue-300",
    collapseContainer: "border border-blue-400 bg-blue-50",
    collapseHeader: "bg-blue-200 text-blue-900 cursor-pointer",
    collapseContent: "bg-blue-100 text-blue-800",
    collapseIcon: "text-blue-700 transition-transform duration-300",
  },

  vibrant: {
    background: "bg-pink-100",
    text: "text-pink-900",
    button: "bg-pink-500 hover:bg-pink-600 active:bg-pink-700 text-white",
    activeTab: "bg-pink-700 text-white font-bold shadow-md",
    sliderTrack: "bg-pink-300",
    sliderFill: "bg-pink-500",
    sliderThumb: "bg-pink-700",
    sliderValue: "bg-pink-800 text-white",
    toggleBackground: "bg-pink-300",
    toggleThumb: "bg-pink-400",
    toggleActive: "bg-pink-500",
    toggleInactive: "bg-pink-200",
    input:
      "border border-pink-400 bg-pink-50 text-pink-900 placeholder-pink-600 focus:ring-2 focus:ring-pink-500",
    dropdownHover: "hover:bg-pink-300",
    collapseContainer: "border border-pink-400 bg-pink-50",
    collapseHeader: "bg-pink-200 text-pink-900 cursor-pointer",
    collapseContent: "bg-pink-100 text-pink-800",
    collapseIcon: "text-pink-700 transition-transform duration-300",
  },

  gray: {
    background: "bg-gray-50",
    text: "text-gray-900",
    button: "bg-gray-300 hover:bg-gray-600 active:bg-gray-700 text-black",
    activeTab: "bg-gray-700 text-white font-bold shadow-md",
    sliderTrack: "bg-gray-300",
    sliderFill: "bg-gray-500",
    sliderThumb: "bg-gray-700",
    sliderValue: "bg-gray-800 text-white",
    toggleBackground: "bg-gray-300",
    toggleThumb: "bg-gray-400",
    toggleActive: "bg-gray-500",
    toggleInactive: "bg-gray-200",
    input:
      "border border-gray-400 bg-gray-100 text-gray-800 placeholder-gray-600 focus:ring-2 focus:ring-gray-500",
    dropdownHover: "hover:bg-gray-300",
    collapseContainer: "border border-gray-400 bg-gray-100",
    collapseHeader: "bg-gray-200 text-gray-900 cursor-pointer",
    collapseContent: "bg-gray-100 text-gray-800",
    collapseIcon: "text-gray-700 transition-transform duration-300",
  },
};
